export const TRIP_REQUEST = "TRIP_REQUEST";
export const TRIP_REQUEST_UPDATE = "TRIP_REQUEST_UPDATE";
export const TRIP_REQUEST_DELETE = "TRIP_REQUEST_DELETE";
export const TRIP_FAILURE = "TRIP_FAILURE";
export const TRIP_UPDATED_SUCCESS = "TRIP_UPDATED_SUCCESS";
export const TRIP_CREATED_SUCCESS = "TRIP_CREATED_SUCCESS";
export const TRIP_DELETE_SUCCESS = "TRIP_DELETE_SUCCESS";
